memory_map:
  boot:
    base_addr: 0x00000000
    size: 0x08006000
    permissions: rw-
  text:
    base_addr: 0x08006000
    permissions: r-x
    is_entry: true
    file: ./firmware/U400.bin
    size: 0x1640d8
  text_tail:
    base_addr: 0x0816b000
    size: 0x95000
    permissions: rw-
  ram:
    base_addr: 0x20000000
    size: 0x40000
    permissions: rw-
  mmio:
    base_addr: 0x40000000
    size: 0x20000000
    permissions: rw-
  mmio_high:
    base_addr: 0xa0000000
    size: 0x20000000
    permissions: rw-
  nvic:
    base_addr: 0xe0000000
    size: 0x10000000
    permissions: rw-
  devinfo:
    base_addr: 0x0fe00000
    size: 0x10000
    permissions: rw-
limits:
  translation_blocks: 3000000
  fuzz_consumption_timeout: 0
entry_point: 0x08019d44
initial_sp: 0x20001200
use_systick: false
use_nvic: false
